### ISSUE TITLE
Create ADR-00 - Using ADRs

### ISSUE THREAD

**Issue by ITDependsQ42022** [ITDependsQ42022/Hey-Blue#1]
This task is to create the initial structure in the repository to hold Architecture Decision Records (i.e. where the Architecture Decision Log will live), and to submit the first ADR.  The first ADR, as is common in projects using ADRs, will simply be the decision to use ADRs along with any details on format/convention and potentially ADL conventions.

**Comment by mgasca** [comment]
As noted this issue and the first ADR is about adoption, template, format, structure.

We all agree that we will use ADRs, so no need to discuss adoptoin

# Template
There are a variety of templates available that we can follow, a good list can be found in the [readme](https://github.com/joelparkerhenderson/architecture-decision-record) of Joel Parker Henderson's ADR repo.

I would suggest that we use the [MADR 3.0 Teamplate](https://adr.github.io/madr/). I particularly like the idea of the shift from purely Architecture to generally significant decisions.  It allows space for recording decisions that are softer, yetstill related to architecture in that it is about providing a solution for the problem at hand.  It provides a simple and sufficient structure, though in addition to the [basic example](https://adr.github.io/madr/#example) we should prefer to add Consequences per the desire of the Kata judges.

I think we should use the [decision records of MADR 3.0 ](https://adr.github.io/madr/decisions/)itself as guidelines for our own ADRs in addition to just the internal document template.  For instance, the concept of [Categories]([url](https://adr.github.io/madr/decisions/0010-support-categories.html)) in the structure of the Architecture Decision Log allows us to convey more through the limited degree of interaction we have with the judges.  Recall that there is no direct interaction before the first round of judging, only what is present in our github repository.

**Comment by kavyashivakumar** [comment]
Agree. i recently adapted madr 3.0 in MS too. and we should definitely go with the latest
