### ISSUE TITLE
Systems

### ISSUE THREAD

**Issue by kapooruma** [ITDependsQ42022/Hey-Blue#8]
**Personas:**
PO
Civilians
Charities
Retail Stores
 
 
**UI**
Connection UI
Rewards History Lookup
 
**Systems**

- Onboarding
      Terms & Conditions
-   -     Data Protection
-   -     Push Notification
-   -     Location Tracker
- 
- Points Management
- Connections Management
- Referrals
- StoreFront Management
- B2B Services
- Connections Report by Zipcode
- Points History/Activity
- Fee Calculation
- Points Redemption
- EOM batch run
- Community Gains
- Community Spend Plan
- Charity - Retail Mapping
- HeyBlue Social Media ( is this an existing system .. Or we responsible to build this as well). If we do, then we need to add to UI
-  
-  
-  

offer these users maximum value to fulfill the intent of logging on the app and turning on their location finder.
 
 
**Service Dependencies**

- Location Tracker

**Comment by mgasca** [comment]
Hey @kapooruma what kind of conversation would you like to have around what you've documented here?

**Comment by kavyashivakumar** [comment]
I think this document needs bit of review for cosmetic changes?

**Comment by kapooruma** [comment]
Yes i wasnt updating this here .. lwmmw take care of it

**Comment by kapooruma** [comment]
Containers

 

Member Management
Members: Civilians, Officers, Storefront, Charity, Municipality

Member Profile Management
Preference Management
For Civilians
Opt In/Out:
Location Tracker
Push Notifications
Enable Officer/Civilian Interactions
For Officer
Registrations should capture enough info of the Officer to prove authenticity of their Role
Opt In/Out:
Location Tracker
Push Notifications
Enable Officer/Civilian Interactions
For Charity
Enroll to Integrate with HeyBlue
Registrations should capture enough info of the Charity to prove authenticity of their NPO
For Municipality
Enroll to Integrate with HeyBlue
 

 

Points Management
 

o    Connection Management

Scope Of Members here: Civilians, Officers

·         Connection List ( with Details including Members involved,  Identified by Connection ID )

 

o    Interaction Management

Scope Of Members here: Civilians, Officers

·         Interaction List ( with Interaction Details including Connection ID, Type of Interaction, Identified by Interaction ID )

 

o    Points Activity Management

·         Member to Points

·         Points Redemption In Store

·         Points Donated To Charity

·         Penalty waived To Civilians by Municipality

 


 

 

Cash Management / Book Keeping
EOM Accounting Batch
Points Usage Aggregation by Store
Expected Transaction Fee ( aka Afiliate Mktg Fee ) By Store
Expected HeyBlue Admin Fee
Expected Community Share
Cash management DashBoard ( For the Treasurer )
Display money to send to Community
Send Payment to Community ( ACH / Check / P2P from Online bank  system )
Post Payment sent, System to note itas posting to Account
On Reciept, Reflect Settled Activity. ( Optionally, could integrate with Yodlee to avoid this manual step )
Reflect Actual Balance
Send Confirmation to StoreFronts ( Send amount expectation Summary & Itemization to Retail )
Display Affirmation from StoreFronts
Run the Reconciliation and determine Confirmation Vs Affirmation Gaps
Do the necessary Adjustments
Receipt of Payment from StoreFront
 

Analytics & Reporting
Site activity
Connections Report by Zipcode
Analytics + Public Data ( Impact of App in community )
Points usage patterns ( civilian, po, business, municipality )
 

Geographic Info System
Social Media Integration
StoreFront Platform
Charity Platform
Municipality Platform
( Nice To Have ) NextBestAction ( Complex Event Processing Platform to generate next Best Action Outcomes ):
Alert HeyBlue Activity around a StoreFront, to promote Registered Storefront to generate more Merchandise Promotions
Send Marketing Materials to non-registered StoreFronts, showing HeyBlue activity around their Store, to encourage registration
Encourage Active Civilians with ways to refer other civilians for additional Points
etc
 

  

 
[Containers.docx](https://github.com/ITDependsQ42022/Hey-Blue/files/9944060/Containers.docx)

**Comment by kapooruma** [comment]
We can close this ... I have created new issue "Create Containers"
